# Generated by Django 4.2.6 on 2023-10-28 09:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0002_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="user",
        ),
    ]
