# Generated by Django 4.2.6 on 2023-10-28 09:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0003_remove_comment_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="likes",
            field=models.IntegerField(default=0),
        ),
    ]
