# Generated by Django 4.2.6 on 2023-10-28 09:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0004_comment_likes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="likes",
        ),
        migrations.AddField(
            model_name="post",
            name="likes",
            field=models.IntegerField(default=0),
        ),
    ]
